### ISSUE TITLE
Not working with Angular 7

### ISSUE THREAD

**Issue by ramreddybandari** [KhaledSMQ/Ng2FormBuilder#9]
When i migrate to the Angular version 7 from 4 it is giving the following error...
ERROR in src/app/formbuilder/form-builder.ts(332,43): error TS2339: Property 'children' does not exist on type '{}'.

**Comment by KhaledSMQ** [comment]
Please use this example.
https://stackblitz.com/edit/angular-ngformbuilder
